### ISSUE TITLE
Warning: array_search() expects at least 2 parameters, 1 given in /home/mcvergec/public_html/app/Controller/Authentication.php on line 177

### ISSUE THREAD

**Issue by sakofchit** [mcverge/Issues#5]
Warning: array_search() expects at least 2 parameters, 1 given in /home/mcvergec/public_html/app/Controller/Authentication.php on line 177

https://www.mcverge.com/user/register

Doesn't seem to have much an impact on forum functionality.

**Comment by Xesau** [comment]
Will be looking into this tonight.

**Comment by sakofchit** [comment]
@Xesau it doesn't seem to be conflicting with anything. I commented out line 178 which removed the error
